packages:
  - packages/*
  - apps/*

catalogs:
  tooling:
    '@types/node': ^25.2.1
    '@types/react': ^19.2.13
    '@types/react-dom': ^19.2.3
    eslint: ^9.39.2
    prettier: ^3.8.1
    tsup: ^8.5.1
    typescript: ^5.9.3
    typescript-eslint: ^8.54.0
    vite: ^7.3.1
    vitest: ^4.0.18
